### ISSUE TITLE
I can't visualizze my point cloud 

### ISSUE THREAD

**Issue by assia855** [mafda/augmented_reality_101#10]
Thanks for sharing this interesting repos. I would like to reproduce your results with my data, I have a point cloud but I can't visualize it at the last frame. I don't understand what should I change to visualize my point cloud. 
Thanks in advance.

**Comment by mafda** [comment]
Thank you for your interest in my repository.

As I understand it, that error is occurring in the code "ar_python3_opencv4.py". Did you try the code with the data I provided? Did it work? Did you use the same shared virtual environment in the repository?

Thanks.

**Comment by assia855** [comment]
Thanks for your answer. I solve it by augmenting the scale of my point cloud. Now I can visualize my point cloud.
